# Generated by Django 4.1.5 on 2023-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_school_school_type_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
