# Generated by Django 4.1.5 on 2023-02-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_student_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceset',
            name='a',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='b',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='c',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='d',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='e',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='f',
            field=models.CharField(default='', editable=False, max_length=256),
        ),
    ]
