# Generated by Django 4.1.5 on 2023-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_choiceset_a_alter_choiceset_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceset',
            name='a',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='b',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='c',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='d',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='e',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='f',
            field=models.CharField(default='', editable=False, max_length=512),
        ),
    ]
