# Generated by Django 4.1.5 on 2023-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_choiceset_a_alter_choiceset_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('used', models.BooleanField()),
                ('pin', models.CharField(max_length=32)),
            ],
        ),
    ]
