# Generated by Django 4.1.5 on 2023-02-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_resultpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('S', 'Senior'), ('J', 'Junior')], default='Senior', max_length=16),
        ),
        migrations.AlterField(
            model_name='resultpin',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
