# Generated by Django 4.1.5 on 2023-02-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_subject_category_alter_resultpin_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
