# Generated by Django 4.1.5 on 2023-02-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_registration_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name_plural': 'Payment Types'},
        ),
        migrations.AlterModelOptions(
            name='resultpin',
            options={'verbose_name_plural': 'Result Pins'},
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.choiceset', verbose_name='options'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.subject'),
        ),
    ]
