# Generated by Django 4.1.5 on 2023-03-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
