# Generated by Django 4.1.5 on 2023-03-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_student_teacher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexampaper',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
