# Generated by Django 4.1.5 on 2023-03-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_studentexampaper_submission_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexampaper',
            name='score',
        ),
    ]
