# Generated by Django 4.1.5 on 2023-03-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_remove_studentexampaper_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
