# Generated by Django 4.1.5 on 2023-03-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_relations', '0008_officer_active'),
        ('exam', '0014_alter_registration_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_relations.officer'),
        ),
    ]
