# Generated by Django 4.1.5 on 2023-03-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_student_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexampaper',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
