# Generated by Django 4.1.5 on 2023-03-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_studentexampaper_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexampaper',
            name='score',
        ),
    ]
