# Generated by Django 4.1.5 on 2023-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_remove_studentexampaper_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexampaper',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
