# Generated by Django 4.1.5 on 2023-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_studentexampaper_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexampaper',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
