# Generated by Django 4.1.5 on 2023-03-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_alter_studentexampaper_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexampaper',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
