# Generated by Django 4.1.5 on 2023-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('S', 'Senior'), ('J', 'Junior'), ('P', 'Primary')], default='Senior', max_length=16),
        ),
    ]
