# Generated by Django 4.1.5 on 2023-04-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_subject_image_alter_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpin',
            name='use_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultpin',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
    ]
