# Generated by Django 4.1.5 on 2023-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_studentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
