# Generated by Django 4.1.5 on 2023-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_studentreport_average'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentreport',
            options={'verbose_name_plural': 'Student Reports'},
        ),
        migrations.AddField(
            model_name='studentreport',
            name='real_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
