# Generated by Django 4.1.5 on 2023-03-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0015_student_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('message', models.TextField(editable=False, max_length=1024)),
                ('category', models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Good', 'Good')], max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('levels', models.ManyToManyField(help_text='The classes broadcast concerns', to='exam.level')),
            ],
        ),
    ]
