# Generated by Django 4.1.5 on 2023-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='exam_write_requirement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast',
            name='result_check_requirement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='message',
            field=models.TextField(max_length=1024),
        ),
    ]
