# Generated by Django 4.1.5 on 2023-05-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_broadcast_viewed_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='viewed_students',
        ),
    ]
