# Generated by Django 4.1.5 on 2023-02-24 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_relations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='student',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='students',
        ),
        migrations.AddField(
            model_name='message',
            name='student_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET, related_name='messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officer',
            name='student_accounts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='as_officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
