# Generated by Django 4.1.5 on 2023-02-26 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_relations', '0004_messagecategory_alter_message_student_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagecategory',
            options={'verbose_name_plural': 'Message Categories'},
        ),
        migrations.AlterField(
            model_name='officer',
            name='student_accounts',
            field=models.ManyToManyField(related_name='officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
