# Generated by Django 4.1.5 on 2023-03-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_relations', '0005_alter_messagecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_relations.officer'),
        ),
        migrations.AddField(
            model_name='officer',
            name='duties',
            field=models.ManyToManyField(to='customer_relations.messagecategory'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=1024)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_relations.message')),
            ],
        ),
    ]
