# Generated by Django 4.1.5 on 2023-03-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_relations', '0006_message_officer_officer_duties_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='officer',
        ),
    ]
