# Generated by Django 4.1.5 on 2023-03-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_relations', '0007_remove_message_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
