# Generated by Django 4.1.5 on 2023-02-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guardian_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
