# Generated by Django 4.1.5 on 2023-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_useraccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
