# Generated by Django 4.1.5 on 2023-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_useraccount_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_executive',
            field=models.BooleanField(default=False),
        ),
    ]
