# Generated by Django 4.1.5 on 2023-02-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_title', models.CharField(help_text='Use a name that describes the policy', max_length=64)),
                ('exam_duration', models.DurationField()),
                ('number_of_questions', models.IntegerField()),
                ('registration_limit', models.IntegerField()),
                ('result_collection_fees', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Policy Groups',
            },
        ),
    ]
